- hosts: robots
  remote_user: pi
  gather_facts: no

  vars_files:
    - app_vars.yml

  tasks:
    - local_action: osx_say msg="Deploying..."

    - name: Updating repository
      git:  repo="{{ project_repo }}" dest="{{ src_root }}" update=yes

    - name: Update virtualenv
      pip: requirements="{{ project_root }}/requirements.txt" virtualenv="{{virtualenv_root}}"

    - name: Restarting dozer 
      service: name={{ dozer_service }} state=restarted
      sudo: yes

    - local_action: osx_say msg="Deploy successful."

