- hosts: robots
  remote_user: pi
  gather_facts: no

  vars_files:
    - app_vars.yml

  tasks:
    - local_action: osx_say msg="Deploying..."

    - apt: update_cache=yes
      sudo: yes

    - apt: name=git state=present
      sudo: yes

    - apt: name=postgresql state=present
      sudo: yes

    - apt: name=nginx state=present
      sudo: yes

    - apt: name=uwsgi state=present
      sudo: yes

    - apt: name=python-virtualenv state=present
      sudo: yes

    - apt: name=python-dev state=present
      sudo: yes

    - name: Updating repository
      git:  repo="{{ project_repo }}" dest="{{ src_root }}" update=yes

    - name: Create virtualenv
      pip: requirements="{{ project_root }}/requirements.txt" virtualenv="{{virtualenv_root}}"

    - name: Restarting dozer 
      service: name={{ dozer_service }} state=restarted
      sudo: yes

    - local_action: osx_say msg="Deploy successful."

