- hosts: robots
  remote_user: pi
  gather_facts: no

  vars_files:
    - app_vars.yml

  tasks:
    - local_action: osx_say msg="Updating..."

    - name: Updating repository
      git:  repo="{{ project_repo }}" dest="{{ project_root }}" update=yes

    - name: Create virtualenv
      pip: requirements="{{ src_root }}/robot/requirements.txt" virtualenv="{{virtualenv_root}}"

    - name: Restarting dozer 
      service: name={{ dozer_service_name }} state=restarted
      sudo: yes

    - local_action: osx_say msg="Update successful."

